### ISSUE TITLE
Orc Eclipse plug-in doesn't launch Orc programs in Eclipse Luna

### ISSUE THREAD

**Issue by GoogleCodeExporter** [orc-lang/orc#133]
```
Procedure to Repeat:
1. Install JDK 8 and Eclipse Luna (4.4).
2. Attempt to run any Orc program in Eclipse.

Expected / Actual Results:
The launch fails.  NoClassDefFoundError in the plug-in method that sets up the 
class path to run the Orc program.

Version and Platform:
Orc version 2.1.0 rev. 3306
Orc Eclipse Plug-In version: 2.1.0.201309212307
Eclipse version 4.4.0.I20140606-1215
Eclipse Standard/SDK Version: Luna Release (4.4.0) Build id: 20140612-0600
Java JDK 1.8.0_20-b26
OS X 10.9.5

Reporter's Comments:
Reported by dkitchin 31 Aug 2014 18:14 CDT

Don't know if this is related to Eclipse 4.4 or Java 8....

Stack trace:
java.lang.NoClassDefFoundError: 
org/eclipse/osgi/internal/baseadaptor/DefaultClassLoader
	at edu.utexas.cs.orc.orceclipse.launch.OrcLaunchDelegate.getAbsoluteClasspathForClass(OrcLaunchDelegate.java:195)
	at edu.utexas.cs.orc.orceclipse.launch.OrcLaunchDelegate.launch(OrcLaunchDelegate.java:154)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:883)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.ClassNotFoundException: 
org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader cannot be found by 
edu.utexas.cs.orc.orceclipse_2.1.0.201309212307
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:336)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:328)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

```

Original issue reported on code.google.com by `jthywissen` on 26 Sep 2014 at 9:12

**Comment by jthywiss** [comment]
Fixed in 91ea088f31b0d10726ee7c589b3d4d59295929f9
