### ISSUE TITLE
Orc wiki update is failing

### ISSUE THREAD

**Issue by jthywiss** [orc-lang/orc#142]
Attempts to edit the Orc wiki result in the following stacktrace when pressing the "edit" button:

    HTTP ERROR: 500
    
    PWC6033: Unable to compile class for JSP
    
    PWC6197: An error occurred at line: 29 in the jsp file: /Edit.jsp
    PWC6199: Generated servlet error:
    The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files
    
    RequestURI=/wiki/Edit.jsp
    
    Caused by:
    
    org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP
    
    PWC6197: An error occurred at line: 29 in the jsp file: /Edit.jsp
    PWC6199: Generated servlet error:
    The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files
    
    
    	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:107)
    	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:280)
    	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:350)
    	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:411)
    	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:592)
    	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:344)
    	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:470)
    	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:364)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
    	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1097)
    	at com.ecyrd.jspwiki.ui.WikiServletFilter.doFilter(WikiServletFilter.java:174)
    	at com.ecyrd.jspwiki.ui.WikiJSPFilter.doFilter(WikiJSPFilter.java:111)
    	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1088)
    	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
    	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:729)
    	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
    	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:206)
    	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    	at org.mortbay.jetty.Server.handle(Server.java:324)
    	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)
    	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:829)
    	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:513)
    	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
    	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)
    	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:395)
    	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:488)

**Comment by jthywiss** [comment]
Suspected classpath problem.  This also may be a Java 8 compatibility problem.

**Comment by arthurp** [comment]
I think it might be an issue with code being built against Java 8 classes with a Java 7 compiler. This issue is related to default method implementations on Java 8 interfaces.

See https://developer.ibm.com/answers/questions/182450/the-type-javalangcharsequence-cannot-be-resolved-i/ for more details.

**Comment by jthywiss** [comment]
Fixed.  Jetty needed to be upgraded.

Note: orc.csres is still running the old Jetty until I clean up our orchard.war packaging.

**Comment by jthywiss** [comment]
This is now in production.
